name: Publish Release
on: workflow_dispatch

jobs:
  build:
    uses: ithundxr/workflows/.github/workflows/java-build.yml@main
    with:
      java-version: 21
      is-release: true
      release-task: publishMods
    secrets:
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
